USER_CONFLICT = "User with {0} username is already exist.", 409
USER_NOT_FOUND = "User with {0} is not exist in database.", 404
USER_CREATION = "User was created Successfully.", 201
USER_DELETE = "The user is deleted.", 200
USER_UPDATE = "The user is successfully updated.", 200
PERMISSION = "Invalid credentials.", 401
USER_LOGIN = "The user is successfully logged in.", 200
USER_LOGOUT = "The user is successfully logged out.", 200
WRONG_DATA="wrong username or password."
SOMETHING_WENT_WRONG="Please try Again Later . Something went wrong."
TYPE_PASSWORD="Please type password again."
ACCOUNT_REQUIRED="You don't have any account . please make one."
